[package]
name = "kya-oe"
version = "0.0.1"
edition = "2024"
authors = ["Purging Light Tech <purging-light-tech@gmx.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
